name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: pytest

      - name: Install dependencies
        run: |
          pip install pytest pylint bandit flake8

      - name: Run tests
        run: pytest

      - name: Run pylint
        run: pylint JeuxPour2 || true

      - name: Run bandit
        run: bandit -r JeuxPour2 || true

      - name: Run flake8
        run: flake8 JeuxPour2 || true 